using System;
using System.Collections.Generic;
using System.Text;

namespace SRTPluginProviderRE7.Structs
{
    class Items
    {
        public static Dictionary<string, int> ItemSlots = new Dictionary<string, int>()
        {
            {"Bar", 1},
            {"ChainSaw", 1},
            {"CircularSaw", 1},
            {"HandAxe", 1},
            {"Knife", 1},
            {"MiaKnife", 1},
            {"Burner", 2},
            {"GrenadeLauncher", 2},
            {"Handgun_Albert", 1},
            {"Handgun_Albert_Reward", 1},
            {"Handgun_G17", 1},
            {"Handgun_M19", 1},
            {"Handgun_MPM", 1},
            {"MachineGun", 2},
            {"Magnum", 2},
            {"Shotgun_DB", 2},
            {"Shotgun_M37", 2},
            {"BlueBlaster", 1},
            {"HyperBlaster", 1},
            {"RedBlaster", 1},
            {"LiquidBomb", 1},
            {"UnlimitedAmmo", 1},
            {"AcidBulletS", 1},
            {"BurnerBullet", 1},
            {"FlameBulletS", 1},
            {"HandgunBullet", 1},
            {"HandgunBulletL", 1},
            {"MachineGunBullet", 1},
            {"MagnumBullet", 1},
            {"ShotgunBullet", 1},
            {"EyeDrops", 1},
            {"Herb", 1},
            {"RemedyL", 1},
            {"RemedyM", 1},
            {"AlphaGrass", 1},
            {"BookDefence01", 1},
            {"BookDefence02", 1},
            {"Depressant", 1},
            {"Stimulant", 1},
            {"EasyBoots", 1},
            {"Coin", 1},
            {"CoinOld", 1},
            {"GoodLuckCoinA", 1},
            {"GoodLuckCoinB", 1},
            {"GoodLuckCoinC", 1},
            {"GoodLuckCoinD", 1},
            {"GoodLuckCoinE", 1},
            {"PowerUpCoin01A", 1},
            {"PowerUpCoin01B", 1},
            {"Alcohol", 1},
            {"AlloyClay", 1},
            {"ChemicalL", 1},
            {"ChemicalM", 1},
            {"ChemicalS", 1},
            {"Flower", 1},
            {"Gunpowder", 1},
            {"Magnesium", 1},
            {"RepairKit", 1},
            {"MailMia", 1},
            {"MiaDriversLicense", 1},
            {"ProposalBookFf", 1},
            {"3CrestKeyA", 1},
            {"3CrestKeyB", 1},
            {"3CrestKeyC", 1},
            {"CabinKey", 1},
            {"CylinderKey", 1},
            {"EntranceHallKey", 1},
            {"EthanCarKey", 1},
            {"FloorDoorKey", 1},
            {"LucasCardKey", 1},
            {"LucasCardKey2", 1},
            {"MasterKey", 1},
            {"MorgueKey", 1},
            {"SpareKey", 1},
            {"TalismanKey", 1},
            {"WorkroomKey", 1},
            {"TreasureMap01", 1},
            {"TreasureMap02", 1},
            {"TreasureMap03", 1},
            {"Battery", 1},
            {"BrokenHandgun_M19", 1},
            {"BrokenShotgun_DB", 2},
            {"BurnerPartsA", 1},
            {"BurnerPartsB", 1},
            {"ChainCutter", 2},
            {"Crank", 1},
            {"DummyAxe", 1},
            {"EvCable", 1},
            {"EvelynRadar1", 1},
            {"EvelynRadar2", 1},
            {"EvelynRadar3", 1},
            {"EvelynRadar4", 1},
            {"EvOpener", 1},
            {"Fuse", 1},
            {"FuseCh4", 1},
            {"Lantern", 1},
            {"PendulumClock", 1},
            {"SerumComplete", 1},
            {"SerumMaterialA", 1},
            {"SerumMaterialB", 1},
            {"SerumTypeE", 1},
            {"SilhouettePazzlePiece", 1},
            {"SilhouettePazzlePieceOldHouse", 1},
            {"Timebomb", 1},
            {"ToyShotgun", 2},
            {"EthanLeg", 1},
            {"HandCutOff", 1},
            {"Balloonbomb", 1},
            {"Candle", 1},
            {"Glasses", 1},
            {"ScrewFinger", 1},
            {"Quill", 1},
            {"Valve", 1},
            {"SpringCoil", 1},
            {"SaveTape", 1},
            {"SupplyBoxA", 1},
            {"SupplyBoxOpenedA", 1},
            {"SupplyBoxB", 1},
            {"SupplyBoxOpenedB", 1},
            {"SupplyBoxC", 1},
            {"SupplyBoxOpenedC", 1},
            {"FoundFootage000", 1},
            {"FoundFootage010", 1},
            {"FoundFootage020", 1},
            {"FoundFootage030", 1},
            {"FoundFootage040", 1},
            {"FoundFootage050", 1},
            //NOT A HERO
            {"CKnife", 1},
            {"Handgun_Albert_C", 1},
            {"Shotgun_Albert", 2},
            {"Grenadebomb", 1},
            {"Thermatebomb", 1},
            {"Stangrenadebomb", 1},
            {"SiteScopeB", 1},
            {"SiteScopeC", 1},
            {"AlbertHandgunBullet", 1},
            {"AlbertHandgunBulletL", 1},
            {"AlbertShotgunBullet", 1},
            {"KeyItem02Ch8", 1},
            {"KeyItem03Ch8", 1},
            {"KeyItem05Ch8", 1},
            {"Ch8CageKey", 1},
            {"MineMasterKey", 1},
            {"RemedyAmpoulesM", 1},
            {"RemedyAmpoulesL", 1},
            {"UmbrellaFile00", 1},
            {"UmbrellaFile01", 1},
            {"BookDefenceJustGuard", 1},
            {"DepressantAmpoules", 1},
            {"StimulantAmpoules", 1},
        };

        public enum ItemType
        {
            ITEM,
            WEAPON,
            STACKABLE
        }

        public static Dictionary<string, ItemType> ItemTypes = new Dictionary<string, ItemType>()
        {
            {"Bar", ItemType.WEAPON},
            {"ChainSaw", ItemType.WEAPON},
            {"CircularSaw", ItemType.WEAPON},
            {"HandAxe", ItemType.WEAPON},
            {"Knife", ItemType.WEAPON},
            {"MiaKnife", ItemType.WEAPON},
            {"Burner", ItemType.WEAPON},
            {"GrenadeLauncher", ItemType.WEAPON},
            {"Handgun_Albert", ItemType.WEAPON},
            {"Handgun_Albert_Reward", ItemType.WEAPON},
            {"Handgun_G17", ItemType.WEAPON},
            {"Handgun_M19", ItemType.WEAPON},
            {"Handgun_MPM", ItemType.WEAPON},
            {"MachineGun", ItemType.WEAPON},
            {"Magnum", ItemType.WEAPON},
            {"Shotgun_DB", ItemType.WEAPON},
            {"Shotgun_M37", ItemType.WEAPON},
            {"BlueBlaster", ItemType.WEAPON},
            {"HyperBlaster", ItemType.WEAPON},
            {"RedBlaster", ItemType.WEAPON},
            {"LiquidBomb", ItemType.WEAPON},
            {"UnlimitedAmmo", ItemType.ITEM},
            {"AcidBulletS", ItemType.STACKABLE},
            {"BurnerBullet", ItemType.STACKABLE},
            {"FlameBulletS", ItemType.STACKABLE},
            {"HandgunBullet", ItemType.STACKABLE},
            {"HandgunBulletL", ItemType.STACKABLE},
            {"MachineGunBullet", ItemType.STACKABLE},
            {"MagnumBullet", ItemType.STACKABLE},
            {"ShotgunBullet", ItemType.STACKABLE},
            {"EyeDrops", ItemType.STACKABLE},
            {"Herb", ItemType.STACKABLE},
            {"RemedyL", ItemType.STACKABLE},
            {"RemedyM", ItemType.STACKABLE},
            {"AlphaGrass", ItemType.ITEM},
            {"BookDefence01", ItemType.ITEM},
            {"BookDefence02", ItemType.ITEM},
            {"Depressant", ItemType.STACKABLE},
            {"Stimulant", ItemType.STACKABLE},
            {"EasyBoots", ItemType.ITEM},
            {"CoinOld", ItemType.ITEM},
            {"Coin", ItemType.STACKABLE},
            {"GoodLuckCoinA", ItemType.ITEM},
            {"GoodLuckCoinB", ItemType.ITEM},
            {"GoodLuckCoinC", ItemType.ITEM},
            {"GoodLuckCoinD", ItemType.ITEM},
            {"GoodLuckCoinE", ItemType.ITEM},
            {"PowerUpCoin01A", ItemType.ITEM},
            {"PowerUpCoin01B", ItemType.ITEM},
            {"Alcohol", ItemType.ITEM},
            {"AlloyClay", ItemType.ITEM},
            {"ChemicalL", ItemType.ITEM},
            {"ChemicalM", ItemType.ITEM},
            {"ChemicalS", ItemType.ITEM},
            {"Flower", ItemType.ITEM},
            {"Gunpowder", ItemType.STACKABLE},
            {"Magnesium", ItemType.STACKABLE},
            {"RepairKit", ItemType.STACKABLE},
            {"MailMia", ItemType.ITEM},
            {"MiaDriversLicense", ItemType.ITEM},
            {"ProposalBookFf", ItemType.ITEM},
            {"3CrestKeyA", ItemType.ITEM},
            {"3CrestKeyB", ItemType.ITEM},
            {"3CrestKeyC", ItemType.ITEM},
            {"CabinKey", ItemType.ITEM},
            {"CylinderKey", ItemType.STACKABLE},
            {"EntranceHallKey", ItemType.ITEM},
            {"EthanCarKey", ItemType.ITEM},
            {"FloorDoorKey", ItemType.ITEM},
            {"LucasCardKey", ItemType.ITEM},
            {"LucasCardKey2", ItemType.ITEM},
            {"MasterKey", ItemType.ITEM},
            {"MorgueKey", ItemType.ITEM},
            {"SpareKey", ItemType.STACKABLE},
            {"TalismanKey", ItemType.ITEM},
            {"WorkroomKey", ItemType.ITEM},
            {"TreasureMap01", ItemType.ITEM},
            {"TreasureMap02", ItemType.ITEM},
            {"TreasureMap03", ItemType.ITEM},
            {"Battery", ItemType.ITEM},
            {"BrokenHandgun_M19", ItemType.ITEM},
            {"BrokenShotgun_DB", ItemType.ITEM},
            {"BurnerPartsA", ItemType.ITEM},
            {"BurnerPartsB", ItemType.ITEM},
            {"ChainCutter", ItemType.ITEM},
            {"Crank", ItemType.ITEM},
            {"DummyAxe", ItemType.ITEM},
            {"EvCable", ItemType.ITEM},
            {"EvelynRadar1", ItemType.ITEM},
            {"EvelynRadar2", ItemType.ITEM},
            {"EvelynRadar3", ItemType.ITEM},
            {"EvelynRadar4", ItemType.ITEM},
            {"EvOpener", ItemType.ITEM},
            {"Fuse", ItemType.ITEM},
            {"FuseCh4", ItemType.ITEM},
            {"Lantern", ItemType.ITEM},
            {"PendulumClock", ItemType.ITEM},
            {"SerumComplete", ItemType.ITEM},
            {"SerumMaterialA", ItemType.ITEM},
            {"SerumMaterialB", ItemType.ITEM},
            {"SerumTypeE", ItemType.ITEM},
            {"SilhouettePazzlePiece", ItemType.ITEM},
            {"SilhouettePazzlePieceOldHouse", ItemType.ITEM},
            {"Timebomb", ItemType.ITEM},
            {"ToyShotgun", ItemType.ITEM},
            {"EthanLeg", ItemType.ITEM},
            {"HandCutOff", ItemType.ITEM},
            {"Balloonbomb", ItemType.ITEM},
            {"Candle", ItemType.ITEM},
            {"Glasses", ItemType.ITEM},
            {"ScrewFinger", ItemType.ITEM},
            {"Quill", ItemType.ITEM},
            {"Valve", ItemType.ITEM},
            {"SpringCoil", ItemType.ITEM},
            {"SaveTape", ItemType.STACKABLE},
            {"SupplyBoxA", ItemType.ITEM},
            {"SupplyBoxOpenedA", ItemType.ITEM},
            {"SupplyBoxB", ItemType.ITEM},
            {"SupplyBoxOpenedB", ItemType.ITEM},
            {"SupplyBoxC", ItemType.ITEM},
            {"SupplyBoxOpenedC", ItemType.ITEM},
            {"FoundFootage000", ItemType.ITEM},
            {"FoundFootage010", ItemType.ITEM},
            {"FoundFootage020", ItemType.ITEM},
            {"FoundFootage030", ItemType.ITEM},
            {"FoundFootage040", ItemType.ITEM},
            {"FoundFootage050", ItemType.ITEM},
            //NOT A HERO
            {"CKnife", ItemType.WEAPON},
            {"Handgun_Albert_C", ItemType.WEAPON},
            {"Shotgun_Albert", ItemType.WEAPON},
            {"Grenadebomb", ItemType.STACKABLE},
            {"Thermatebomb", ItemType.STACKABLE},
            {"Stangrenadebomb", ItemType.STACKABLE},
            {"SiteScopeB", ItemType.ITEM},
            {"SiteScopeC", ItemType.ITEM},
            {"AlbertHandgunBullet", ItemType.STACKABLE},
            {"AlbertHandgunBulletL", ItemType.STACKABLE},
            {"AlbertShotgunBullet", ItemType.STACKABLE},
            {"KeyItem02Ch8", ItemType.ITEM},
            {"KeyItem03Ch8", ItemType.ITEM},
            {"KeyItem05Ch8", ItemType.ITEM},
            {"Ch8CageKey", ItemType.ITEM},
            {"MineMasterKey", ItemType.ITEM},
            {"RemedyAmpoulesM", ItemType.STACKABLE},
            {"RemedyAmpoulesL", ItemType.STACKABLE},
            {"UmbrellaFile00", ItemType.ITEM},
            {"UmbrellaFile01", ItemType.ITEM},
            {"BookDefenceJustGuard", ItemType.ITEM},
            {"DepressantAmpoules", ItemType.ITEM},
            {"StimulantAmpoules", ItemType.ITEM},
        };

        public static Dictionary<string, string> ItemDictionary = new Dictionary<string, string>()
        {
            {"Bar", "Crowbar"},
            {"ChainSaw", "Chain Saw"},
            {"CircularSaw", "Circular Saw"},
            {"HandAxe", "Axe"},
            {"Knife", "Knife"},
            {"MiaKnife", "Survival Knife"},
            {"Burner", "Flamethrower"},
            {"GrenadeLauncher", "Grenade Launcher"},
            {"Handgun_Albert", "Albert-01"},
            {"Handgun_Albert_Reward", "Albert-01 R"},
            {"Handgun_G17", "G17 Handgun"},
            {"Handgun_M19", "M19 Handgun"},
            {"Handgun_MPM", "MPM Handgun"},
            {"MachineGun", "P19 Machine Gun"},
            {"Magnum", "44 Mag"},
            {"Shotgun_DB", "M21 Shotgun"},
            {"Shotgun_M37", "M37 Shotgun"},
            {"BlueBlaster", "BlueBlaster"},
            {"HyperBlaster", "HyperBlaster"},
            {"RedBlaster", "RedBlaster"},
            {"LiquidBomb", "Remote Bomb"},
            {"UnlimitedAmmo", "Infinite Ammo"},
            {"AcidBulletS", "Neuro Rounds"},
            {"BurnerBullet", "Burner Fuel"},
            {"FlameBulletS", "Flame Rounds"},
            {"HandgunBullet", "Handgun Ammo"},
            {"HandgunBulletL", "Enhanced Handgun Ammo"},
            {"MachineGunBullet", "Machine Gun Ammo"},
            {"MagnumBullet", "44 Mag Ammo"},
            {"ShotgunBullet", "Shotgun Ammo"},
            {"EyeDrops", "Psychostimulants"},
            {"Herb", "Herb"},
            {"RemedyL", "Strong First Aid Med"},
            {"RemedyM", "First Aid Med"},
            {"AlphaGrass", "X-ray Glasses"},
            {"BookDefence01", "The Secrets Of Defense"},
            {"BookDefence02", "The Essence Of Defense"},
            {"Depressant", "Stabilizer - Faster Reload"},
            {"Stimulant", "Steroids - Increase Max Health"},
            {"EasyBoots", "Walking Shoes"},
            {"CoinOld", "Dirty Coin"},
            {"Coin", "Antique Coin"},
            {"GoodLuckCoinA", "Defense Coin"},
            {"GoodLuckCoinB", "Attack Coin"},
            {"GoodLuckCoinC", "Instinct Coin"},
            {"GoodLuckCoinD", "GoodLuckCoinD"},
            {"GoodLuckCoinE", "GoodLuckCoinE"},
            {"PowerUpCoin01A", "Assault Coin"},
            {"PowerUpCoin01B", "Iron Defense Coin"},
            {"Alcohol", "Solid Fuel"},
            {"AlloyClay", "Chilled Chem Fluid"},
            {"ChemicalL", "Seperating Agent"},
            {"ChemicalM", "Strong Chem Fluid"},
            {"ChemicalS", "Chem Fluid"},
            {"Flower", "Supplements"},
            {"Gunpowder", "Gun Powder"},
            {"Magnesium", "Weak Acid"},
            {"RepairKit", "Gun Repair Kit"},
            {"MailMia", "Email from Mia"},
            {"MiaDriversLicense", "Mia Driving License"},
            {"ProposalBookFf", "Project Proposal"},
            {"3CrestKeyA", "Blue Dogs Head"},
            {"3CrestKeyB", "White Dogs Head"},
            {"3CrestKeyC", "Red Dogs Head"},
            {"CabinKey", "Captains Cabin Locker Key"},
            {"CylinderKey", "Lock Pick"},
            {"EntranceHallKey", "Ox Statuette"},
            {"EthanCarKey", "Car Key"},
            {"FloorDoorKey", "Hatch Key"},
            {"LucasCardKey", "Keycard - Blue"},
            {"LucasCardKey2", "Keycard - Red"},
            {"MasterKey", "Snake Key"},
            {"MorgueKey", "Scorpion Key"},
            {"SpareKey", "Corrosive"},
            {"TalismanKey", "Crow Key"},
            {"WorkroomKey", "Dissection Room Key"},
            {"TreasureMap01", "Treasure Photo - Morgue"},
            {"TreasureMap02", "Treasure Photo - Old House"},
            {"TreasureMap03", "Treasure Photo - Master Bedroom"},
            {"Battery", "Battery"},
            {"BrokenHandgun_M19", "Broken Handgun"},
            {"BrokenShotgun_DB", "Broken Shotgun"},
            {"BurnerPartsA", "Burner Grip"},
            {"BurnerPartsB", "Burner Nozzle"},
            {"ChainCutter", "Bolt Cutters"},
            {"Crank", "Crank"},
            {"DummyAxe", "Toy Axe"},
            {"EvCable", "Power Cable"},
            {"EvelynRadar1", "Eveline Strange Bottle"},
            {"EvelynRadar2", "Eveline Tissue Samples (1)"},
            {"EvelynRadar3", "Eveline Tissue Samples (2)"},
            {"EvelynRadar4", "Eveline Tissue Samples (3)"},
            {"EvOpener", "Lug Wrench"},
            {"Fuse", "Fuse"},
            {"FuseCh4", "General Purpose Fuse"},
            {"Lantern", "Lantern"},
            {"PendulumClock", "Clock Pendulum"},
            {"SerumComplete", "Serum Complete"},
            {"SerumMaterialA", "D-Series Arm"},
            {"SerumMaterialB", "D-Series Head"},
            {"SerumTypeE", "E-Necrotoxin"},
            {"SilhouettePazzlePiece", "Wooden Statuette"},
            {"SilhouettePazzlePieceOldHouse", "Stone Statuette"},
            {"Timebomb", "Time bomb"},
            {"ToyShotgun", "Model Shotgun"},
            {"EthanLeg", "Ethans Leg"},
            {"HandCutOff", "Ethans Hand"},
            {"Balloonbomb", "Balloon"},
            {"Candle", "Candle"},
            {"Glasses", "Dirty Telescope"},
            {"ScrewFinger", "Dummy Finger"},
            {"Quill", "Quill Pen"},
            {"Valve", "Valve Handle"},
            {"SpringCoil", "Winding Key"},
            {"SaveTape", "Cassette Tape (Save)"},
            {"SupplyBoxA", "Box A (2xHerb,RemedyM,RemedyL)"},
            {"SupplyBoxOpenedA", "Box A (Opened)"},
            {"SupplyBoxB", "Box B (Gunpowder,10xHandgunBullet,3xHandgunBulletL)"},
            {"SupplyBoxOpenedB", "Box B (Opened)"},
            {"SupplyBoxC", "Box C (RemedyM,7xShotgunBullet)"},
            {"SupplyBoxOpenedC", "Box C (Opened)"},
            {"FoundFootage000", "Derelict House Footage (1)"},
            {"FoundFootage010", "FoundFootage010"},
            {"FoundFootage020", "Derelict House Footage (2)"},
            {"FoundFootage030", "Mia"},
            {"FoundFootage040", "Happy Birthday"},
            {"FoundFootage050", "Old Videotape"},
            //NOT A HERO
            {"CKnife", "Tactical Knife"},
            {"Handgun_Albert_C", "Samurai Edge"},
            {"Shotgun_Albert", "Thor's Hammer"},
            {"Grenadebomb", "Grenade"},
            {"Thermatebomb", "Incendiary Grenade"},
            {"Stangrenadebomb", "Neuro-Stun Grenade"},
            {"SiteScopeB", "Thor's Hammer Sight B"},
            {"SiteScopeC", "Thor's Hammer Sight C"},
            {"AlbertHandgunBullet", "AW Handgun Ammo"},
            {"AlbertHandgunBulletL", "Anti-Regen Ammo (RAMRODs)"},
            {"AlbertShotgunBullet", "AW Shotgun Ammo"},
            {"KeyItem02Ch8", "Antique Coin"},
            {"KeyItem03Ch8", "Crank"},
            {"KeyItem05Ch8", "Gear"},
            {"Ch8CageKey", "Cell Key"},
            {"MineMasterKey", "Clown Key"},
            {"RemedyAmpoulesM", "Med Injector"},
            {"RemedyAmpoulesL", "Strong Med Injector"},
            {"UmbrellaFile00", "Briefing Document"},
            {"UmbrellaFile01", "Letter Regarding Umbrella's Goals"},
            {"BookDefenceJustGuard", "Easy Guard"},
            {"DepressantAmpoules", "Stabilizer - Faster Reload"},
            {"StimulantAmpoules", "Steroids - Increase Max Health"},
        };
    }
}
